"""
MAIRA — Report Generator
Produces a clean markdown report from all MAIRA outputs.
Ready for paper supplementary material or sharing.
"""

import json
import os
from pathlib import Path
from datetime import datetime


def load_json(path: str) -> dict:
    try:
        with open(path) as f:
            return json.load(f)
    except:
        return {}


def generate_report(root: str) -> str:
    root = Path(root)
    now  = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Load all MAIRA outputs
    advice    = load_json(root / "maira_research_advice.json")
    decisions = load_json(root / "maira_dataset_decisions.json")

    project_type = advice.get("project_type", "UNKNOWN")
    gaps         = advice.get("gaps_found", [])
    ai_advice    = advice.get("advice", "No advice generated yet.")

    lines = []

    # Header
    lines += [
        "# MAIRA Research Report",
        f"**Generated:** {now}",
        f"**Project:** `{root}`",
        f"**Project Type:** {project_type}",
        "",
        "---",
        "",
    ]

    # Experiment Gaps
    lines += [
        "## Experiment Gaps Detected",
        "",
        "MAIRA identified the following untested experiment combinations:",
        "",
    ]
    for g in gaps:
        lines.append(f"- {g}")
    if not gaps:
        lines.append("- No gaps detected.")
    lines.append("")

    # Dataset Decisions
    lines += [
        "---",
        "",
        "## Dataset Architecture Decisions",
        "",
        "| File | Type | Total | Split | Train | Val | Test |",
        "|------|------|-------|-------|-------|-----|------|",
    ]
    for d in decisions:
        lines.append(
            f"| `{d.get('file_path','')}` "
            f"| {d.get('dataset_type','')} "
            f"| {d.get('total_records','')} "
            f"| {d.get('split_ratio','')} "
            f"| {d.get('train_size','')} "
            f"| {d.get('val_size','')} "
            f"| {d.get('test_size','')} |"
        )
    lines.append("")

    # Justifications
    lines += [
        "### Split Justifications",
        "",
    ]
    for d in decisions:
        lines.append(f"**{d.get('file_path', '')}**")
        for j in d.get("justification", []):
            lines.append(f"- {j}")
        lines.append("")

    # AI Advice
    lines += [
        "---",
        "",
        "## AI Research Advisor Output",
        "",
        ai_advice,
        "",
        "---",
        "",
        "*Generated by MAIRA — ML Agentic Intelligence for Research Automation*",
        "*Zero instrumentation required. Point at any ML project folder.*",
    ]

    return "\n".join(lines)


def save_report(root: str) -> str:
    report   = generate_report(root)
    out_path = Path(root) / "maira_report.md"
    with open(out_path, "w") as f:
        f.write(report)
    print(f"  Report saved to {out_path}")
    return str(out_path)


def print_report(root: str) -> None:
    print("\n" + "="*60)
    print("  MAIRA — Report Generator")
    print("="*60 + "\n")
    print(generate_report(root))


if __name__ == "__main__":
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    print_report(root)
    save_report(root)